---
title: "Basic Nonlinear"
author: "Ethan Stuart"
date: "3/28/2018"
output: word_document
---

```{r}
## Theory HW Fx expansions I
crops <- read.table(header=FALSE,text='
4 3
1 2
8 5
3 3
3 1
5 4
6 5
3 2
2 1
3 4
')
names(crops)<- c("Yield","Handlines")
plot(crops$Handlines,crops$Yield) # Wow! Curvature!
#2
bigx <- matrix(c(
  1,3,9,
  1,2,4,
  1,5,25,
  1,3,9,
  1,1,1,
  1,4,16,
  1,5,25,
  1,2,4,
  1,1,1,
  1,4,16),ncol=3,byrow=TRUE)
bigy <- matrix(crops$Yield,ncol=1,byrow=T)
#3
(BETAs <-solve(t(bigx)%*%bigx)%*%t(bigx)%*%bigy)
#4
n <- 10
(ssquared <-(1/(n-3))*t(bigy-bigx%*%BETAs)%*%(bigy-bigx%*%BETAs))
#5
out1 <- lm(Yield~Handlines+I(Handlines^2),data=crops,x=TRUE,se.fit=TRUE)
out1$x
t(bigy-out1$x%*%out1$coefficients)%*%(bigy-out1$x%*%out1$coefficients)
out.reduced <- lm(Yield~Handlines, data=crops,x=TRUE)
out.reduced$x
t(bigy-out.reduced$x%*%out.reduced$coefficients)%*%(bigy-out.reduced$x%*%out.reduced$coefficients)

anova(out1,out.reduced)
#Fstat=4.360. Pval=.07519. 
```

Part 2
```{r}
#6
url <- "http://grimshawville.byu.edu/NFLinSLC.txt" #accessed 3/28/2018
nfl <- read.csv(url)
out.nfl <- lm(Audience~TotalPoints+I(TotalPoints^2)+I(TotalPoints^3)+I(TotalPoints^4)+I(TotalPoints^5)+I(TotalPoints^6),data=nfl,x=TRUE)
median(abs(predict(out.nfl))) #61.808

library(car)
library(MASS)
library(splines)
#7
out.nfl.ns <- lm(Audience~ns(TotalPoints,3),data=nfl)  
median(abs(predict(out.nfl.ns))) #63.123

x.star <- seq(25,65,length.out = 1001)
yhat <- predict(out.nfl,newdata=data.frame(TotalPoints=x.star))
yhat.ns <- predict(out.nfl.ns,newdata=data.frame(TotalPoints=x.star))

plot(Audience~TotalPoints,data=nfl,xlim=c(25,65))
lines(x.star,yhat.ns,col="sienna")
lines(x.star,yhat,col="royalblue4",type="l")

legend("topleft",legend=c("Data","Polynomial","Splines"),col=c("black","royalblue4","sienna"),pch=c(1,NA,NA),lty=c(NA,1,1))
```